FROM python:3.8-slim-buster

RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app
EXPOSE 8080
CMD [ "python", "main.py" ]
