version: "3"
services:
   redis: 
     image: redislabs/redismod
     deploy:
      resources:
        limits:
          cpus: '2'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 128M
     ports:
       - '6379:6379'
     restart: on-failure
     network_mode: "host" 
   redisinsight:
    image: redislabs/redisinsight:latest
    ports:
    - '8001:8001'
    network_mode: "host"
   web:
    build: .
    network_mode: "host"
    deploy:
     resources:
      limits:
       cpus: '2'
       memory: 128M
      reservations:
       cpus: '0.05'
       memory: 64M
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
     - redis
    healthcheck:
          test: curl --fail http://localhost:5000/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 5
          start_period: 60s
    restart: on-failure 