services:
   redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379'
     restart: on-failure 
   redisinsight:
    image: redislabs/redisinsight:latest
    ports:
    - '8001:8001'
   web:
    build: .
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.5
    ports:
      - "8080:5000"
    volumes:
      - .:/code
    depends_on:
     - redis
    healthcheck:
          test: curl --fail http://localhost:8080/ || exit 1
          interval: 40s
          timeout: 30s
          retries: 5
          start_period: 60s
    restart: on-failure 